// 定义页面导航
//
export default [
  { text: "学习指南", link: "/", activeMatch: "" },
  {
    text: "备忘录📕",
    link: "/notes/",
    activeMatch: "/notes/",
  },
  {
    text: "Rust 官方",
    items: [
      { text: "Rust 官网", link: "https://www.rust-lang.org/" },
      { text: "Rust 源码", link: "https://github.com/rust-lang/rust/blob/master/library/" },
      { text: "Rust blog", link: "https://blog.rust-lang.org/" },
      { text: "Rust 标准库", link: "https://doc.rust-lang.org/std/" },
      { text: "Rust Playground", link: "https://play.rust-lang.org/" },
      { text: "Rust 参考", link: "https://doc.rust-lang.org/reference/" },
      { text: "Rust 秘典（死灵书）", link: "https://doc.rust-lang.org/nomicon/" },
      { text: "Rust 未稳定特性手册", link: "https://doc.rust-lang.org/nightly/unstable-book/" },
      { text: "Rust 版本指南", link: "https://doc.rust-lang.org/nightly/edition-guide/" },
      { text: "Rust RFCs", link: "https://rust-lang.github.io/rfcs/" },
      { text: "Rust 社区", link: "https://users.rust-lang.org/" },
      { text: "cargo 文档", link: "https://doc.rust-lang.org/cargo/" },
      { text: "rustc 文档", link: "https://doc.rust-lang.org/rustc/" },
      { text: "rustdoc 文档", link: "https://doc.rust-lang.org/rustdoc/" },
      { text: "clippy 文档", link: "https://doc.rust-lang.org/clippy/" },
      { text: "Rust 编译错误索引", link: "https://doc.rust-lang.org/error-index.html" },
      { text: "This Week in Rust", link: "https://this-week-in-rust.org" },
      { text: "Asynchronous Book", link: "https://rust-lang.github.io/async-book/" },
      { text: "Rust 编译器开发", link: "https://rustcrustc.github.io/rustc-dev-guide-zh/" },
      { text: "Rust Forge", link: "https://forge.rust-lang.org/" },
      { text: "Rust bindgen", link: "https://rust-lang.github.io/rust-bindgen/" },
      { text: "Rust 书籍📚", link: "https://www.rust-lang.org/learn" },
    ],
  },
  {
    text: "Rust 开源书籍",
    items: [
      { text: "Rust By Example", link: "https://github.com/rust-lang/rust-by-example" },
      { text: "Rust 程序设计（中文版）", link: "https://kaisery.github.io/trpl-zh-cn/" },
      { text: "Comprehensive Rust 🦀", link: "https://google.github.io/comprehensive-rust/" },
      { text: "Rust 设计模式", link: "https://github.com/Fomalhauthmj/patterns/" },
      { text: "Rust Primer", link: "https://rustcc.gitbooks.io/rustprimer" },
      { text: "Rust 宏小册", link: "https://zjp-cn.github.io/tlborm/" },
      { text: "Rust 语言圣经", link: "https://course.rs/" },
      { text: "Rusty Book", link: "https://rusty.course.rs/" },
      { text: "Rust By Practice", link: "https://zh.practice.rs/why-exercise.html" },
      { text: "Rust Cookbook", link: "https://rust-lang-nursery.github.io/rust-cookbook/" },
      { text: "The Rust Performance Book", link: "https://nnethercote.github.io/perf-book/profiling.html" },
      { text: "Rust Atomics and Locks", link: "https://rustcc.github.io/Rust_Atomics_and_Locks/" },
    ],
  },
];
